[timescale]
uot = 50

[infection_process]
r_prior_mean = 1
r_prior_sd = 1
sigma_rt_prior = 0.1
dur_inf = 7

sigma_i_first_obs_prior_mode = 0
sigma_i_first_obs_prior_sd = 0.5
i_first_obs_certainty = 5
  ## effective number of binomial trials
  ## in beta prior centered on estimated i_first_obs (estimated) /n

mean_initial_exp_growth_rate_prior_mean = 0
mean_initial_exp_growth_rate_prior_sd = 0.01
sigma_initial_exp_growth_rate_prior_mode = 0
sigma_initial_exp_growth_rate_prior_sd = 0.05

autoreg_rt_a = 2 # shape1 parameter of autoreg term on Rt trend
autoreg_rt_b = 40 # shape2 parameter of autoreg on Rt trend
  # mean = a/(a+b) = 0.05, stdv = sqrt(a)/b = sqrt(2)/40 = 0.035
autoreg_rt_subpop_a = 1 # shape1 parameter of autoreg term on difference between
  # R(t) ref and R(t) subpop
autoreg_rt_subpop_b = 4 # shape2 parameter of autoreg term on difference between
# R(t) ref and R(t) subpop

# Normal prior on fixed offset between central log scale R(t) and reference pop
offset_ref_log_r_t_prior_mean = 0
offset_ref_log_r_t_prior_sd = 0.2

# Normal prior on fixed offset between central logit scale i_first_obs/n and reference pop i_first_obs/n
offset_ref_logit_i_first_obs_prior_mean = 0
offset_ref_logit_i_first_obs_prior_sd = 0.25

# Normal prior on fixed offset between central initial exponential growth rate
# and reference population initial exponential growth rate
offset_ref_initial_exp_growth_rate_prior_mean = 0
offset_ref_initial_exp_growth_rate_prior_sd = 0.025

autoreg_p_hosp_a = 1 # shape1 parameter of autoreg term on IHR(t) trend
autoreg_p_hosp_b = 100 # shape2 parameter of autoreg term on IHR(t) trend
eta_sd_sd = 0.01
infection_feedback_prior_logmean = 0 # log(mode) + q^2 mode = 1, q = 3
infection_feedback_prior_logsd = 3

[hospital_admission_observation_process]
# Hospitalization parameters (informative priors)
# IHR estimate from: https://www.nature.com/articles/s41467-023-39661-5
p_hosp_mean = 0.01
p_hosp_sd_logit = 0.3

# time variation in p_hosp
p_hosp_w_sd_sd = 0.01

inv_sqrt_phi_prior_mean = 0.1 # 1 / sqrt(100)
inv_sqrt_phi_prior_sd = 0.1414214 # 1 / sqrt(50)
hosp_wday_effect_prior_alpha = [5, 5, 5, 5, 5, 5, 5]
# centered on equal effects for all days

[wastewater_observation_process]
ml_of_ww_per_person_day = 22.7e4
t_peak_mean = 5
t_peak_sd = 1
viral_peak_mean = 5.1
viral_peak_sd = 0.5
duration_shedding_mean = 17
duration_shedding_sd = 3
log10_g_prior_mean = 12
log10_g_prior_sd = 2
log_g_prior_mean = 27.63102 # 12 * log(10)
log_g_prior_sd = 4.60517 # 2 * log(10)

mode_sigma_ww_site_prior_mode = 1
mode_sigma_ww_site_prior_sd = 1
sd_log_sigma_ww_site_prior_mode = 0
sd_log_sigma_ww_site_prior_sd = 0.693 # log(2)

ww_site_mod_sd_sd = 0.25
log_phi_g_prior_mean = -2.302585 # log(0.1)
# prior mean in individual level dispersion
# in fecal shedding
log_phi_g_prior_sd = 5 # wide std


[continuous_distribution_parameters]
  # Generation Interval
  # From: Park, Sang Woo, et al. "Inferring the differences in incubation-period
  # and generation-interval distributions of the Delta and Omicron variants of
  # SARS-CoV-2." Proceedings of the National Academy of Sciences 120.22 (2023):
  # e2221887120.
  # from the object in Fig 4F corresponding to between household transmission
  # in Omicron https://github.com/parksw3/omicron-generation/blob/d36d4568bfd3b3d389b30282758b9c322cfe2b9f/figure/compare.R#L175 #nolint

 mu_gi = 0.92877
 sigma_gi = 0.526 # (using lognormal CDF and Park CIs of 2.7 and 3.2)
 gt_max = 15 # number of daily bins for discretization

  # Incubation period parameters
  # From: Park, Sang Woo, et al. "Inferring the differences in incubation-period
  # and generation-interval distributions of the Delta and Omicron variants of
  # SARS-CoV-2." Proceedings of the National Academy of Sciences 120.22 (2023):
  # e2221887120.
 r = 0.15
 backward_shape = 1.5
 backward_scale = 3.6

  # Symptom onset to hospital admission delay parameters
  # From fitting a negative binomial to data from
  # Danache et al
  # https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0261428
 neg_binom_mu = 6.98665
 neg_binom_size = 2.490848
